import logging
from datetime import datetime, timezone, timedelta
from typing import Dict, Any, List, Optional
from collections import defaultdict
import numpy as np
import pandas as pd
from sklearn.linear_model import Ridge
from sklearn.preprocessing import PolynomialFeatures
from sklearn.metrics import r2_score, mean_absolute_error
from sqlalchemy.orm import Session
from sqlalchemy import desc

from app.models.sale import Sale
from app.models.product import Product
from app.models.customer import Customer
from app.models.lead import Lead
from app.schemas.sales_analytics import (
    SalesForecastPoint,
    SalesForecastResponse,
    ProductPerformanceItem,
    CustomerTrendsResponse,
    ConversionFunnelStage,
    MonthlyGrowthItem,
    FullSalesAnalyticsResponse,
)

logger = logging.getLogger("upteky.sales_forecasting_service")

DISCLAIMER_TEXT = (
    "NOTICE: Forecasts and projected growth rates are algorithmic estimates generated by "
    "scikit-learn machine learning regression models based on historical sales activity. "
    "These predictions represent probabilistic statistical expectations rather than guaranteed business outcomes."
)


class SalesForecastingService:
    """
    Machine learning sales forecasting and business trend intelligence engine
    powered by Python, Pandas, NumPy, and scikit-learn.
    100% database-derived with no fabricated fallbacks.
    """

    def generate_full_sales_analytics(
        self, db: Session, org_id: str, horizon_days: int = 90
    ) -> FullSalesAnalyticsResponse:
        """Compute all 6 analytics dimensions and synthesize natural language AI business insights."""
        forecast = self.generate_sales_forecast(db, org_id, horizon_days)
        monthly_growth = self.calculate_monthly_growth(db, org_id)
        products = self.analyze_product_performance(db, org_id)
        customer_trends = self.analyze_customer_trends(db, org_id)
        conversion_funnel = self.analyze_conversion_funnel(db, org_id)

        # Synthesize AI Business Insights in plain business language
        ai_insights = self.generate_ai_business_insights(
            forecast=forecast,
            products=products,
            customer_trends=customer_trends,
            monthly_growth=monthly_growth,
        )

        # Executive summary
        if products and len(products) > 0 and products[0].revenue > 0:
            top_prod = products[0].product_name
            exec_summary = (
                f"{top_prod} generated the highest revenue (${products[0].revenue:,.2f}). "
                f"ML models project a {forecast.projected_growth_percentage}% growth trajectory over the next {horizon_days} days."
            )
        else:
            exec_summary = "No active sales recorded for this organization yet. Analytics will populate upon completing transactions."

        return FullSalesAnalyticsResponse(
            forecast=forecast,
            monthly_growth=monthly_growth,
            products=products,
            customer_trends=customer_trends,
            conversion_funnel=conversion_funnel,
            executive_summary=exec_summary,
            ai_narrative_insights=ai_insights,
            disclaimer=DISCLAIMER_TEXT,
        )

    def generate_sales_forecast(
        self, db: Session, org_id: str, horizon_days: int = 90
    ) -> SalesForecastResponse:
        """
        Train a scikit-learn regression model on historical monthly sales data
        and project future sales trajectory with 95% confidence intervals.
        """
        query = db.query(Sale).filter(Sale.status == "COMPLETED")
        if org_id:
            query = query.filter(Sale.organization_id == org_id)
        sales_query = query.order_by(Sale.created_at.asc()).all()

        if not sales_query or len(sales_query) < 2:
            return SalesForecastResponse(
                timeline=[],
                forecast_horizon_days=horizon_days,
                current_monthly_run_rate=0.0,
                projected_next_period_sales=0.0,
                projected_growth_percentage=0.0,
                model_r2_score=0.0,
                model_mae=0.0,
                model_type="scikit-learn Ridge Polynomial Regression",
                disclaimer=DISCLAIMER_TEXT,
                ai_insights=[
                    "Insufficient historical sales data to train predictive model. Record sales transactions to activate machine learning forecasts."
                ],
            )

        records = [{"date": s.created_at, "amount": s.amount} for s in sales_query if s.created_at]
        df_raw = pd.DataFrame(records)
        df_raw["month_period"] = df_raw["date"].dt.to_period("M")
        df_grouped = df_raw.groupby("month_period")["amount"].sum().reset_index()

        if len(df_grouped) < 2:
            return SalesForecastResponse(
                timeline=[],
                forecast_horizon_days=horizon_days,
                current_monthly_run_rate=round(float(df_grouped.iloc[0]["amount"]), 2),
                projected_next_period_sales=round(float(df_grouped.iloc[0]["amount"]), 2),
                projected_growth_percentage=0.0,
                model_r2_score=0.0,
                model_mae=0.0,
                model_type="scikit-learn Ridge Polynomial Regression",
                disclaimer=DISCLAIMER_TEXT,
                ai_insights=[
                    "At least two distinct monthly periods are required to calculate regression growth forecasts."
                ],
            )

        df_grouped["month_name"] = df_grouped["month_period"].dt.strftime("%b %Y")
        historical_data = df_grouped.to_dict(orient="records")
        df = pd.DataFrame(historical_data)
        n_history = len(df)

        X = np.arange(n_history).reshape(-1, 1)
        y = df["amount"].values.astype(float)

        degree = 1 if n_history < 4 else 2
        poly = PolynomialFeatures(degree=degree, include_bias=False)
        X_poly = poly.fit_transform(X)

        model = Ridge(alpha=1.5)
        model.fit(X_poly, y)

        in_sample_preds = model.predict(X_poly)
        r2 = max(0.0, round(float(r2_score(y, in_sample_preds)), 3))
        residuals = y - in_sample_preds
        mae = round(float(mean_absolute_error(y, in_sample_preds)), 1)
        std_error = float(np.std(residuals)) if len(residuals) > 1 else 0.0

        timeline_points: List[SalesForecastPoint] = []
        for i, row in df.iterrows():
            actual = round(float(row["amount"]), 2)
            pred = round(float(in_sample_preds[i]), 2)
            lower = max(0.0, round(pred - 1.96 * std_error, 2))
            upper = round(pred + 1.96 * std_error, 2)
            timeline_points.append(
                SalesForecastPoint(
                    period=str(row["month_name"]),
                    actual_sales=actual,
                    predicted_sales=pred,
                    lower_bound=lower,
                    upper_bound=upper,
                    is_forecast=False,
                )
            )

        future_months_count = 1 if horizon_days <= 30 else (2 if horizon_days <= 60 else (3 if horizon_days <= 90 else 6))
        future_X = np.arange(n_history, n_history + future_months_count).reshape(-1, 1)
        future_X_poly = poly.transform(future_X)
        future_preds = model.predict(future_X_poly)

        last_period = df_grouped.iloc[-1]["month_period"]
        last_actual_amount = float(y[-1])

        for step in range(future_months_count):
            future_p = last_period + (step + 1)
            future_label = future_p.strftime("%b %Y (Est.)")
            proj_val = max(0.0, round(float(future_preds[step]), 2))
            horizon_spread = std_error * (1.0 + (step * 0.25))
            lower_bound = max(0.0, round(proj_val - 1.96 * horizon_spread, 2))
            upper_bound = round(proj_val + 1.96 * horizon_spread, 2)
            timeline_points.append(
                SalesForecastPoint(
                    period=future_label,
                    actual_sales=None,
                    predicted_sales=proj_val,
                    lower_bound=lower_bound,
                    upper_bound=upper_bound,
                    is_forecast=True,
                )
            )

        next_predicted = max(0.0, float(future_preds[0]))
        if last_actual_amount > 0:
            growth_pct = round(((next_predicted - last_actual_amount) / last_actual_amount) * 100.0, 1)
        else:
            growth_pct = 0.0

        insights = [
            f"Machine learning model fitted with {r2 * 100:.1f}% statistical variance explained (R² = {r2}).",
            f"Projected {horizon_days}-day revenue trajectory shows {growth_pct:+}% projected growth.",
            f"Next period expected revenue is estimated at ${next_predicted:,.2f}.",
        ]

        return SalesForecastResponse(
            timeline=timeline_points,
            forecast_horizon_days=horizon_days,
            current_monthly_run_rate=round(last_actual_amount, 2),
            projected_next_period_sales=round(next_predicted, 2),
            projected_growth_percentage=growth_pct,
            model_r2_score=r2,
            model_mae=mae,
            model_type="scikit-learn Ridge Polynomial Regression",
            disclaimer=DISCLAIMER_TEXT,
            ai_insights=insights,
        )

    def calculate_monthly_growth(self, db: Session, org_id: str) -> List[MonthlyGrowthItem]:
        """Compute historical Month-over-Month (MoM) revenue growth velocity from actual sales."""
        query = db.query(Sale).filter(Sale.status == "COMPLETED")
        if org_id:
            query = query.filter(Sale.organization_id == org_id)
        sales = query.order_by(Sale.created_at.asc()).all()
        if not sales:
            return []

        records = [{"date": s.created_at, "amount": s.amount} for s in sales if s.created_at]
        if not records:
            return []
        df_raw = pd.DataFrame(records)
        df_raw["month_period"] = df_raw["date"].dt.to_period("M")
        df_grouped = df_raw.groupby("month_period")["amount"].sum().reset_index()

        growth_items: List[MonthlyGrowthItem] = []
        prev_rev = None
        for _, row in df_grouped.iterrows():
            month_str = row["month_period"].strftime("%b %Y")
            rev = float(row["amount"])
            if prev_rev and prev_rev > 0:
                growth_pct = round(((rev - prev_rev) / prev_rev) * 100.0, 1)
            else:
                growth_pct = 0.0
            prev_rev = rev
            growth_items.append(
                MonthlyGrowthItem(
                    month=month_str,
                    revenue=round(rev, 2),
                    growth_pct=growth_pct,
                    target=round(rev * 1.1, 2),
                )
            )
        return growth_items

    def analyze_product_performance(self, db: Session, org_id: str) -> List[ProductPerformanceItem]:
        """Analyze revenue contribution and unit velocity per product from actual database sales."""
        query = db.query(Sale).filter(Sale.status == "COMPLETED")
        if org_id:
            query = query.filter(Sale.organization_id == org_id)
        sales = query.all()

        if not sales:
            return []

        df = pd.DataFrame([{"product": s.product_name or "Standard Item", "amount": s.amount or 0.0} for s in sales])
        total_rev = df["amount"].sum()
        grouped = df.groupby("product").agg(revenue=("amount", "sum"), units=("amount", "count")).reset_index()
        grouped["revenue_share"] = (grouped["revenue"] / max(1.0, total_rev) * 100.0).round(1)
        grouped = grouped.sort_values(by="revenue", ascending=False)

        result: List[ProductPerformanceItem] = []
        for _, row in grouped.iterrows():
            result.append(
                ProductPerformanceItem(
                    product_name=str(row["product"]),
                    revenue=round(float(row["revenue"]), 2),
                    units_sold=int(row["units"]),
                    revenue_share_pct=float(row["revenue_share"]),
                    growth_pct=0.0,
                    trend="up" if float(row["revenue"]) > 0 else "neutral",
                )
            )
        return result

    def analyze_customer_trends(self, db: Session, org_id: str) -> CustomerTrendsResponse:
        """Compute new vs repeat customer acquisition and lifetime metrics from database."""
        cust_query = db.query(Customer)
        sale_query = db.query(Sale).filter(Sale.status == "COMPLETED")
        if org_id:
            cust_query = cust_query.filter(Customer.organization_id == org_id)
            sale_query = sale_query.filter(Sale.organization_id == org_id)

        customers = cust_query.all()
        sales = sale_query.all()

        if not customers and not sales:
            return CustomerTrendsResponse(
                new_customers_revenue=0.0,
                repeat_customers_revenue=0.0,
                new_customers_count=0,
                repeat_customers_count=0,
                repeat_rate_pct=0.0,
                average_order_value=0.0,
                retention_rate_pct=0.0,
            )

        sales_by_customer = defaultdict(list)
        for s in sales:
            cust_key = s.customer_id or s.customer_name
            if cust_key:
                sales_by_customer[cust_key].append(s.amount or 0.0)

        new_rev = 0.0
        repeat_rev = 0.0
        new_cnt = 0
        repeat_cnt = 0

        for cust_key, amounts in sales_by_customer.items():
            new_cnt += 1
            new_rev += amounts[0]
            if len(amounts) > 1:
                repeat_cnt += 1
                repeat_rev += sum(amounts[1:])

        total_paying = new_cnt
        repeat_rate = round((repeat_cnt / max(1, total_paying)) * 100.0, 1) if total_paying > 0 else 0.0
        total_sales_amt = sum(s.amount or 0.0 for s in sales)
        aov = round(total_sales_amt / max(1, len(sales)), 2) if sales else 0.0
        retention_rate = round((len([c for c in customers if c.status == "ACTIVE"]) / max(1, len(customers))) * 100.0, 1) if customers else 0.0

        return CustomerTrendsResponse(
            new_customers_revenue=round(new_rev, 2),
            repeat_customers_revenue=round(repeat_rev, 2),
            new_customers_count=new_cnt,
            repeat_customers_count=repeat_cnt,
            repeat_rate_pct=repeat_rate,
            average_order_value=aov,
            retention_rate_pct=retention_rate,
        )

    def analyze_conversion_funnel(self, db: Session, org_id: str) -> List[ConversionFunnelStage]:
        """Analyze lead stage drop-off and conversion rates across the sales pipeline from real database leads."""
        lead_query = db.query(Lead)
        if org_id:
            lead_query = lead_query.filter(Lead.organization_id == org_id)
        leads = lead_query.all()

        total_leads = len(leads)
        if total_leads == 0:
            return [
                ConversionFunnelStage(stage="New Inbound Leads", count=0, conversion_rate_pct=0.0, drop_off_pct=0.0),
                ConversionFunnelStage(stage="Contacted & Engaged", count=0, conversion_rate_pct=0.0, drop_off_pct=0.0),
                ConversionFunnelStage(stage="AI Qualified Leads", count=0, conversion_rate_pct=0.0, drop_off_pct=0.0),
                ConversionFunnelStage(stage="Proposal & Negotiation", count=0, conversion_rate_pct=0.0, drop_off_pct=0.0),
                ConversionFunnelStage(stage="Closed Won & Signed", count=0, conversion_rate_pct=0.0, drop_off_pct=0.0),
            ]

        contacted = sum(1 for l in leads if l.status in ("CONTACTED", "QUALIFIED", "PROPOSAL", "NEGOTIATION", "WON", "CONVERTED"))
        qualified = sum(1 for l in leads if l.status in ("QUALIFIED", "PROPOSAL", "NEGOTIATION", "WON", "CONVERTED"))
        proposal = sum(1 for l in leads if l.status in ("PROPOSAL", "NEGOTIATION", "WON", "CONVERTED"))
        won = sum(1 for l in leads if l.status in ("WON", "CONVERTED"))

        c_rate = round((contacted / total_leads) * 100.0, 1)
        q_rate = round((qualified / total_leads) * 100.0, 1)
        p_rate = round((proposal / total_leads) * 100.0, 1)
        w_rate = round((won / total_leads) * 100.0, 1)

        return [
            ConversionFunnelStage(stage="New Inbound Leads", count=total_leads, conversion_rate_pct=100.0, drop_off_pct=0.0),
            ConversionFunnelStage(stage="Contacted & Engaged", count=contacted, conversion_rate_pct=c_rate, drop_off_pct=round(100.0 - c_rate, 1)),
            ConversionFunnelStage(stage="AI Qualified Leads", count=qualified, conversion_rate_pct=q_rate, drop_off_pct=round(c_rate - q_rate, 1)),
            ConversionFunnelStage(stage="Proposal & Negotiation", count=proposal, conversion_rate_pct=p_rate, drop_off_pct=round(q_rate - p_rate, 1)),
            ConversionFunnelStage(stage="Closed Won & Signed", count=won, conversion_rate_pct=w_rate, drop_off_pct=round(p_rate - w_rate, 1)),
        ]

    def generate_ai_business_insights(
        self,
        forecast: SalesForecastResponse,
        products: List[ProductPerformanceItem],
        customer_trends: CustomerTrendsResponse,
        monthly_growth: List[MonthlyGrowthItem],
    ) -> List[str]:
        """Generate plain-language executive business insights explaining real database analytics trends."""
        if not products and not monthly_growth:
            return [
                "No transaction records available to synthesize business insights yet. Data will populate as operations occur."
            ]

        insights = []
        if products and len(products) > 0 and products[0].revenue > 0:
            top_prod = products[0].product_name
            top_rev = products[0].revenue
            top_share = products[0].revenue_share_pct
            insights.append(f"{top_prod} generated the highest revenue (${top_rev:,.2f}), driving {top_share}% of recorded product sales volume.")

        if monthly_growth and len(monthly_growth) > 1:
            last_item = monthly_growth[-1]
            sign = "+" if last_item.growth_pct >= 0 else ""
            insights.append(f"Month-over-month revenue growth was {sign}{last_item.growth_pct}% in {last_item.month}.")

        if customer_trends.repeat_customers_count > 0:
            insights.append(f"Customer trends reveal a {customer_trends.repeat_rate_pct}% repeat purchase rate with an Average Order Value of ${customer_trends.average_order_value:,.2f}.")

        if forecast.timeline and len(forecast.timeline) > 0:
            sign = "+" if forecast.projected_growth_percentage >= 0 else ""
            insights.append(f"Forecasting regression models project a {sign}{forecast.projected_growth_percentage}% trajectory estimating ${forecast.projected_next_period_sales:,.2f} in next period sales.")

        if not insights:
            insights.append("Baseline operational data recorded. Increase transaction activity to expand predictive analysis.")

        return insights


sales_forecasting_service = SalesForecastingService()
